menu:
- {name: 'Hardware', url: '/hardware'}
- {name: 'Software', url: '/software'}
- {name: 'Connect', url: '/connect'}
- {name: 'Support', url: '/support'}
- {name: 'Github', url: '/github'}

social:
- {icon: 'github', link: 'https://github.com/remosim'}
- {icon: 'twitter', link: 'https://twitter.com/remosim'}
- {icon: 'instagram', link: 'https://instagram.com/remosim'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/remosim'}

contacts:
- name: 'Remosim Ltd.'
  email: 'info@remosim.com'
  image: 'assets/img/contact.jpg'
